session_name: default
windows:
    - window_name: vim | bash
      layout: main-vertical
      options:
          main-pane-width: 100
      panes:
          - shell_command:
              - vim
          - shell_command:
              - null
          - shell_command:
              - null
