#!/usr/bin/env bash

e_header "Installing neofetch"
wget -O ~/Downloads/neofetch.tar.gz https://github.com/dylanaraps/neofetch/archive/3.1.0.tar.gz
tar xzf ~/Downloads/neofetch.tar.gz -C ~/Downloads/
cd ~/Downloads/neofetch-*
make install
cd -
