#!/bin/bash

echo Updating OS...
sudo apt-get -qq update
sudo apt-get -qq -y dist-upgrade

apt_packages=()

# Misc.
apt_packages+=(
    awscli
    build-essential
    cmake
    cmatrix
    cowsay
    curl
    default-jdk
    default-jre
    gimp
    git
    golang
    groff
    hollywood
    htop
    id3tool
    imagemagick
    jq
    keepass2
    libreoffice
    mercurial
    nmap
    pidgin
    postgresql
    python-dev
    python3-dev
    python-pip
    python3-pip
    redshift
    vim
    virtualenv
    silversearcher-ag
    sl
    steam
    telnet
    tmux
    tree
    vncviewer
)

# Chrome
echo Downloading Chrome...
wget -O ~/Downloads/google-chrome-stable_current_amd64.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
apt_packages+=(~/Downloads/google-chrome-stable_current_amd64.deb)

# Spotify
echo Adding Spotify to APT...
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys BBEBDCB318AD50EC6865090613B00F1FD2C19886
echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list
apt_packages+=(spotify-client)

if (( ${#apt_packages[@]} > 0 )); then
    echo "Installing APT packages (${#apt_packages[@]})"
    for package in "${apt_packages[@]}"; do
        echo '> "$package"'
        sudo apt-get -y install "$package"
    done
fi

echo Installing tmuxp...
pip3 install tmuxp

echo Installing PIA...
wget -O ~/Downloads/pia-v70-installer-linux.tar.gz https://installers.privateinternetaccess.com/download/pia-v70-installer-linux.tar.gz
tar xzf ~/Downloads/pia-v70-installer-linux.tar.gz
~/Downloads/pia-v70-installer-linux.sh
