#!/usr/bin/env bash

source ~/.dotfiles/bin/shml.sh

pacman_packages=()

# Misc.
pacman_packages+=(
    base-devel
    cmake
    cmatrix
    cowsay
    curl
    dconf
    dconf-editor
    jdk8-openjdk
    jre8-openjdk
    fortune-mod
    gcc
    gimp
    glances
    go
    groff
    htop
    imagemagick
    inetutils
    jq
    keepass
    libreoffice-fresh
    lolcat
    mercurial
    mono
    mono-addins
    mono-basic
    monodevelop
    nmap
    openssh
    pidgin
    postgresql
    python
    python2
    python-pip
    python2-pip
    qbittorrent
    redshift
    gvim
    python-virtualenv
    vlc
    rxvt-unicode
    sl
    steam
    the_silver_searcher
    tigervnc
    tmux
    tree
    unzip
    wget
    xdotool
)

e_header "Updating OS"
revolver --style simpleDots start
sudo pacman -Syu --noconfirm
revolver stop
e_success "OS updated"

if (( ${#pacman_packages[@]} > 0 )); then
    e_header "Installing pacman packages"
    for package in "${pacman_packages[@]}"; do
        revolver --style line start "$package"
        sudo pacman -S --noconfirm "$package"
    done
    e_success "pacman packages installed"
fi

e_header "Making AUR directory"
mkdir ~/.opt

# Chrome
e_header "Installing Chrome"
git clone https://aur.archlinux.org/google-chrome.git ~/.opt/google-chrome/
cd ~/.opt/google-chrome
makepkg -si
cd -
e_success "Chrome installed"

# Spotify
e_header "Installing Spotify"
git clone https://aur.archlinux.org/libopenssl-1.0-compat.git ~/.opt/libopenssl
cd ~/.opt/libopenssl
gpg --recv-keys --keyserver hkp://pgp.mit.edu D9C4D26D0E604491
makepkg -si
cd -
git clone https://aur.archlinux.org/libcurl-openssl-1.0.git ~/.opt/libcurl
cd ~/.opt/libcurl
gpg --recv-keys 5CC908FDB71E12C2
makepkg -si
cd -
git clone https://aur.archlinux.org/spotify.git ~/.opt/spotify
cd ~/.opt/spotify
makepkg -si
cd -
e_success "Spotify installed"

e_header "Installing tmuxp"
pip3 install --user tmuxp
e_success "tmuxp installed"

e_header "Installing PIA"
git clone https://aur.archlinux.org/private-internet-access-vpn.git ~/.opt/pia
cd ~/.opt/pia
makepkg -si
cd -
e_success "PIA installed"

e_header "Installing Emojify (;"
sudo sh -c "curl https://raw.githubusercontent.com/mrowa44/emojify/master/emojify -o /usr/local/bin/emojify && chmod +x /usr/local/bin/emojify"
e_success "Emojify installed $(emojify ":thumbsup:")"

e_header "Installing ttyrec"
git clone https://aur.archlinux.org/ttyrec.git ~/.opt/ttyrec
cd ~/.opt/ttyrec
makepkg -si
cd -
e_success "ttyrec installed"

e_header "Installing ttygif"
git clone https://aur.archlinux.org/ttygif.git ~/.opt/ttygif
cd ~/.opt/ttygif
makepkg -si
cd -
e_success "ttygif installed"

e_header "Install Keepass2 things"
wget -O ~/Downloads/GoogleSyncPlugin-2.1.2.zip https://downloads.sourceforge.net/project/kp-googlesync/GoogleSyncPlugin-2.x/GoogleSyncPlugin-2.1.2.zip
wget -O ~/Downloads/log4net-2.0.8-bin-newkey.zip http://apache.osuosl.org//logging/log4net/binaries/log4net-2.0.8-bin-newkey.zip
unzip -d ~/Downloads/ ~/Downloads/GoogleSyncPlugin-2.1.2.zip
unzip -d ~/Downloads/ ~/Downloads/log4net-2.0.8-bin-newkey.zip
sudo cp ~/Downloads/GoogleSyncPlugin.plgx /usr/share/keepass/Plugins
sudo cp ~/Downloads/log4net-2.0.8/bin/mono/2.0/release/log4net.dll /usr/share/keepass
sudo cp ~/.dotfiles/linux/.lib/System.ServiceModel.Web.dll /usr/share/keepass
e_success "Keepass2 installed"

e_header "Installing neofetch"
git clone https://aur.archlinux.org/neofetch.git ~/.opt/neofetch
cd ~/.opt/neofetch
makepkg -si
cd -
e_success "neofetch installed"

e_header "Adding pipes"
git clone https://github.com/pipeseroni/pipes.sh.git ~/Downloads/pipes
cd ~/Downloads/pipes
sudo make install
cd -

e_header "Installing Reddit Terminal Viewer"
git clone https://aur.archlinux.org/rtv-git.git ~/.opt/rtv
cd ~/.opt/rtv
makepkg -si
cd -
e_success "rtv installed"

e_header "Installing Slack"
git clone https://aur.archlinux.org/slack-desktop.git ~/.opt/slack
cd ~/.opt/slack
makepkg -si
cd -
e_success "slack installed"

e_header "Cleaning up files"
rm -rf ~/Downloads/*
e_success "Files cleaned"
