source /usr/share/zsh/share/antigen.zsh
    
# Load the oh-my-zsh's library
antigen use oh-my-zsh

antigen bundles <<EOBUNDLES
  archlinux
  catimg
  chucknorris
  colored-man-pages
  colorize
  command-not-found
  common-aliases
  encode64
  extract
  git
  github
  git-extras
  git-flow-avh
  gitignore
  go
  history
  heroku
  jsontools
  nyan
  pip
  postgres
  python
  pyenv
  rand-quote
  sprunge
  sudo
  systemd
  taskwarrior
  tmux
  urltools
  vi-mode
  virtualenv
  virtualenvwrapper
  vundle
  web-search
  zsh-autosuggestions
  zsh-syntax-highlighting
EOBUNDLES

# Theme Configuration
POWERLEVEL9K_INSTALLATION_PATH=$ANTIGEN_BUNDLES/bhilburn/powerlevel9k
POWERLEVEL9K_MODE="nerdfont-complete"

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=false

POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL9K_STATUS_VERBOSE=false 
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(status os_icon dir dir_writable vcs command_execution_time)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(background_jobs virtualenv vi_mode)

POWERLEVEL9K_SHOW_CHANGESET=true
POWERLEVEL9K_CHANGESET_HASH_LENGTH=6

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{208}$ %F{223}"

POWERLEVEL9K_OS_ICON_BACKGROUND="246"
POWERLEVEL9K_OS_ICON_FOREGROUND="235"

POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND='237'
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='248'

POWERLEVEL9K_DIR_HOME_BACKGROUND='237'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='237'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='237'
POWERLEVEL9K_DIR_HOME_FOREGROUND='248'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='248'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='248'

# Vi-Mode
POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND='109'
POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND='236'
POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND='246'
POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND='236'

# `git hub colors`
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='239'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='248'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='208'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='236'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='108'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='236'
antigen theme bhilburn/powerlevel9k powerlevel9k

# Tell antigen that you're done
antigen apply

# User configuration

# Use 256 colors
export TERM="xterm-256color"

# Editor
export EDITOR="vim"

# Language
export LANG="en_US"
export LC_ALL="en_US.UTF-8"

# GOPATH
export GOPATH="/home/drew/Projects/go"

# Window
export WINDOWID=$(xdotool getwindowfocus)

# Persistent rehash
zstyle ':completion:*' rehash true

for file in ~/.zsh/{aliases.zsh,functions.zsh}; do
    [ -r "$file" ] && source "$file"
done

if [ -f ~/.extra ]; then
  source ~/.extra
fi

[ -s "/home/drew/.scm_breeze/scm_breeze.sh" ] && source "/home/drew/.scm_breeze/scm_breeze.sh"
