
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=/home/drew/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes

# Theme configuration
# Needs nerd-fonts-complete installed from AUR
# Comment out if not installed
POWERLEVEL9K_MODE="nerdfont-complete"

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=false

POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL9K_STATUS_VERBOSE=false 
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(status os_icon dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(background_jobs virtualenv vi_mode)

POWERLEVEL9K_SHOW_CHANGESET=true
POWERLEVEL9K_CHANGESET_HASH_LENGTH=6

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{208}$ %F{223}"

POWERLEVEL9K_OS_ICON_BACKGROUND="246"
POWERLEVEL9K_OS_ICON_FOREGROUND="235"

POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND='237'
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='248'

POWERLEVEL9K_DIR_HOME_BACKGROUND='237'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='237'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='237'
POWERLEVEL9K_DIR_HOME_FOREGROUND='248'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='248'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='248'

# Vi-Mode
POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND='109'
POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND='236'
POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND='246'
POWERLEVEL9K_VI_MODE_NORMAL_FOREGROUND='236'

# `git hub colors`
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='239'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='248'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='208'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='236'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='108'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='236'

ZSH_THEME="powerlevel9k/powerlevel9k"

# Set list of themes to load
# Setting this variable when ZSH_THEME=random
# cause zsh load theme from this variable instead of
# looking in ~/.oh-my-zsh/themes/
# An empty array have no effect
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
archlinux
catimg
chucknorris
colored-man-pages
colorize
command-not-found
common-aliases
encode64
extract
git
github
git-extras
git-flow-avh
gitignore
go
history
heroku
jsontools
nyan
pip
postgres
python
pyenv
rand-quote
sprunge
sudo
systemd
taskwarrior
tmux
urltools
vi-mode
virtualenv
virtualenvwrapper
vundle
web-search
zsh-autosuggestions
zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# User configuration

# Editor
export EDITOR="vim"

# Language
export LANG="en_US"
export LC_ALL="en_US.UTF-8"

# GOPATH
export GOPATH="/home/drew/Projects/go"

# Window
export WINDOWID=$(xdotool getwindowfocus)

# Persistent rehash
zstyle ':completion:*' rehash true

if [ -f ~/.extra ]; then
  source ~/.extra
fi
