#!/bin/bash

cp ~/.dotfiles/gitconfig ~/.dotfiles/gitconfig_local
echo Name?
read NAME
sed -i -e s/NAME/$NAME/g ~/.dotfiles/gitconfig_local
echo Email?
read EMAIL
sed -i -e s/EMAIL/$EMAIL/g ~/.dotfiles/gitconfig_local
